"""edited shift attributes

Revision ID: 107a387d45b8
Revises: fa62ffa5d731
Create Date: 2023-05-03 14:46:47.049258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '107a387d45b8'
down_revision = 'fa62ffa5d731'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.Time(), nullable=True))
        batch_op.alter_column('start_time',
               existing_type=sa.VARCHAR(),
               type_=sa.Time(),
               existing_nullable=True)
        batch_op.drop_column('start_date_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date_time', sa.DATETIME(), nullable=True))
        batch_op.alter_column('start_time',
               existing_type=sa.Time(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###
