"""edited Shift attributes

Revision ID: 16eb36194e87
Revises: d5393512245c
Create Date: 2023-05-02 17:24:04.127711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16eb36194e87'
down_revision = 'd5393512245c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('start_time', sa.Time(), nullable=True))
        batch_op.drop_column('end_date_time')
        batch_op.drop_column('start_date_time')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date_time', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('end_date_time', sa.DATETIME(), nullable=True))
        batch_op.drop_column('start_time')
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###
