"""added name column to job category

Revision ID: d5393512245c
Revises: 83d3e2c9752a
Create Date: 2023-04-25 22:26:08.618351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5393512245c'
down_revision = '83d3e2c9752a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_categories', schema=None) as batch_op:
        batch_op.drop_column('category_name')

    # ### end Alembic commands ###
