"""edited shift attributes again

Revision ID: ec2ffa0c024e
Revises: 107a387d45b8
Create Date: 2023-05-03 15:05:44.019292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec2ffa0c024e'
down_revision = '107a387d45b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('end_date_time', sa.DateTime(), nullable=True))
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_date')
        batch_op.drop_column('start_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('start_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.TIME(), nullable=True))
        batch_op.drop_column('end_date_time')
        batch_op.drop_column('start_date_time')

    # ### end Alembic commands ###
